# ===============================================
# Javascript/Node.js GitLab CI configuration file
# ===============================================

image: node:10.16.3

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci --cache .node_modules --prefer-offline

lint_and_test:
  script:
    - npm run lint
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/
    reports:
      junit: test-results/mocha/results.xml
