image: node:10.16.3

cache:
  paths:
    - node_modules/

stages:
  - test

install_dependencies:
  stage: test
  script:
    - sudo npm install -g npm@latest
    - npm ci

run_eslint:
  stage: test
  script:
    - npm run lint

run_tests_with_coverage:
  stage: test
  script: 
    - npm run coverage
